# Site
repository: sproogen/resume-theme
favicon: images/km-icon.ico

# Content configuration version
version: 2

# Personal info
name: 박경민
title: Web Developer
email: kyung_za@naver.com
phone: 010-9021-3736
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics

#github_username:  ParkCoder

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://madinthe90.tistory.com/
  
  
  
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 웹 개발자 박경민입니다.

  스킬: <mark>Java</mark> <mark>Spring</mark> <mark>JavaScript</mark> <mark>RDBMS(Oracle, MySQL)</mark> <mark>SQL</mark>  

content:
  # 경력
  - title: 경력 사항 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 아이씨티나인
        # link_text: boringcompany.com
        sub_title: 개발팀 / 대리
        caption: 2021.05 - 현재
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            
            한국환경공단 운영 시스템 개발 및 유지보수, 전자정부프레임워크 기반의 개발        
            
            담당 업무 : 화면·DB 설계 / 풀스택 개발 및 유지보수 / 고객사 커뮤니케이션
                    
#            <mark>2023</mark>   
#             
#            화학안전 사업장 조성 지원 사업 시스템, 화학물질 관리시설 검사 시스템 유지보수 및 추가 사항 개발
#            
#            직급 : 사원 → 대리
#
#            <mark>2022</mark> 
#            
#            화학안전 사업장 조성 지원 사업 시스템 화면, DB 설계 및 개발 (~현재)
#
#            화학안전정책 포럼 개발
#
#            <mark>2021</mark> 
#            
#            화학물질 관리시설 검사 시스템 유지보수 및 추가 사항 개발 (~현재)
#            
#            영화제작 회계 시스템 개발
            
      - layout: left
        title: 이전의 경력
        # link_text: boringcompany.com
#        sub_title: Web Developer
#        caption: 2021.05 - 현재
        quote: >
          "웹 개발자로 전향하기 전의 경력"
        description: | # this will include new lines to allow paragraphs
          <mark>CJ올리브영</mark> 2017.07-2020.04 / 사원 / 영업팀  
          <mark>프리가(레스토랑)</mark> 2016.02-2017.03 / 홀 매니저
  
  # 프로젝트
  - title: 참여 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
#      - layout: left
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
      
      
      
      - layout: left
        title: 화학안전 사업장 조성 지원사업 시스템
        sub_title: 한국환경공단
        caption: 2022.10 - 현재
        link: https://safechem.or.kr/spt
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          "화학물질로부터 안전한 사업장 조성을 위해 보조금을 신청하여 평가하여 지원해주는 시스템의 개발 및 유지보수"
        description: | # this will include new lines to allow paragraphs
         - 사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>jQuery</mark> <mark>Oracle</mark>
         - 역할 : 개발 및 유지보수 (전체 기능 및 페이지), 설계 (초기 설계부터 유지보수 단계의 설계까지 전담)
#         - 참여 인원 : 2명
      
      
      - layout: left
        title: 화학물질 관리시설 검사시스템
        sub_title: 한국환경공단
        caption: 2021.05 - 현재
        link: https://safechem.or.kr
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          "화학물질을 사용하는 시설에 대한 검사 시스템 유지 보수 및 추가 개발"
        description: | # this will include new lines to allow paragraphs
         - 사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>jQuery</mark> <mark>Oracle</mark>
         - 역할 : 유지보수 (관리자 · 사용자), 추가 개발 (화면 · DB 설계)


      - layout: left
        title: 화학안전정책포럼
        sub_title: 환경부
        caption: 2022.04 - 2022.08
        link: https://www.chemnavi.or.kr/forum
        # link_text: Project Website
        quote: >
          "화학안전정책에 관한 포럼 등록 및 관리, 이해당사자들의 의견을 받는 시스템 개발 및 유지보수"
        description: | # this will include new lines to allow paragraphs
         - 사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>jQuery</mark> <mark>Oracle</mark>     
         - 역할 : 페이지 전체 구현 (관리자 · 사용자), 화면 · DB 설계 (초기 설계 이후 변경되는 설계 단계)
#         - 참여 인원 : 4명 (설계 2명, 개발 2명)
          
      - layout: left
        title: 영화제작 회계 시스템
        caption: 2021.09 - 2021.12
        link: https://5friday.kr
#        link: https://5friday.kr/fridayApp
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         "영화 제작 현장에서의 출퇴근 등록 및 관리, 현장에서 사용한 영수증 증빙 및 처리하는 시스템 개발"
        description: | # this will include new lines to allow paragraphs
          - 사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>jQuery</mark> <mark>MySQL</mark>  
          - 역할 : 페이지 전체 구현 (관리자 · 사용자), 화면 · DB 설계 (초기 설계 이후 변경되는 설계 단계)
#          - 참여 인원 : 3명 (설계 2명, 개발 1명)
           
  # 교육과정
  - title: 관련 교육 및 자격증 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      
      - layout: left
        title: 자바기반 웹 개발
        caption: 2020.07 - 2021.01
        sub_title: 더조은컴퓨터학원
        quote: >
          "JAVA, SPRING F/W, ORACLE, MYSQL 중심의 자바 개발자 교육"
        description: | # this will include new lines to allow paragraphs
          - 교육과정 : <mark>Java</mark> <mark>Spring</mark> <mark>Javascript/jQuery</mark> <mark>SQL</mark> <mark>Android Studio</mark> 를 이용한 웹/앱 개발
          
          - 진행프로젝트
          
          - 플라이스캐너 : 항공권 검색 예약 사이트 (2020.09.21-2020.10.14 / 4인)
          
             사용기술 : <mark>Java</mark> <mark>JSP</mark> <mark>Javascript/jQuery</mark> <mark>MySQL</mark>
             
             역할 : 항공권 예약, 결제 <mark>아임포트API 연동</mark>, 내역조회 구현
             
          - 이너뷰 : 건강식품 리뷰 / 구매 플랫폼 (2020.10.19-2020.11.19 / 5인)
          
             사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>Javascript/jQuery</mark> <mark>MySQL</mark>
             
             역할 : 설계 / UI / 카테고리별 상위 제품 노출, 상품 추천 알고리즘, 최근 본 상품, 검색 기능 구현
             
          - keep Memo : 메모장 어플 (2020.11.30-2020.12.11 / 개인)
          
             사용기술 : <mark>Java</mark> <mark>Android Studio</mark> <mark>SQLite</mark>
             
             역할 : 설계 / UI / 메모 CRUD / 어플리케이션 Password 설정
             
          - 리버풀 : 축구팬 페이지 (2020.12.14-2020.12.18 / 개인)
          
             사용기술 : <mark>Java</mark> <mark>Spring</mark> <mark>Javascript/jQuery</mark> <mark>Oracle</mark>
             
             역할 : 설계 / UI /CRUD 구현을 위한 게시판 및 회원가입 / 오픈소스를 이용해 보기 위한 경기 일정 <mark>Fullcalendar</mark>
             
      - layout: left
        title: 정보처리기사
        sub_title: 한국산업인력공단
        description: | # this will include new lines to allow paragraphs
          - 취득일 : 2023년 06월 09일
    
   # 학력
  - title: 학력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
       
      - layout: left
        title: 경동대학교
        sub_title: 외식사업경영학과
        caption: 2009 - 2016
#        quote: >
#          "최종 학력"
        description: | # this will include new lines to allow paragraphs
          - 외식사업경영학과 / 2009년 3월 입학 - 2016년 2월 졸업
#
#      - layout: left
#        title: 일산동고등학교
#        caption: 2006 - 2009
#        sub_title: 문과
#        quote: >
#        description: | # this will include new lines to allow paragraphs
          
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
